name: app
description: "A new Flutter playground."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  collection: ^1.18.0
  dio: ^5.4.1
  onlife_map_view:
    git:
      url: https://github.com/onlifeltd/onlife-flutter-mobile.git
      ref: onlife_map_view
      path: package/onlife_map_view

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

